### ISSUE TITLE
URL is not encoded

### ISSUE THREAD

**Issue by rvaheldendaten** [stefanwalther/qvWebPageViewer2#2]
Hi Stefan!

I have some problems with special characters in the URL.
Changing the line to:

  _this.ExtSettings.WebPageUrl = encodeURI(_this.Layout.Text0.text);

fixed the issue for me.

**Comment by stefanwalther** [comment]
Thx, fixed with version 1.0.4 (0678edfc172a7efbe0f948d60ea31ebba87295f8)
